15036 - 04-Feb-20 00:11:27 - ('magento_config', 'http://www.secretchamber.sg/app/etc/local.xml')
15036 - 04-Feb-20 00:11:27 - ('magento_config', 'https://www.secretchamber.sg/app/etc/local.xml')
15036 - 04-Feb-20 00:11:29 - Redirecting http://www.secretchamber.sg/cgi-bin/cgiecho/mgmzbkix -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:34 - Redirecting https://www.secretchamber.sg/cgi-bin/cgiecho/pcjnymoy -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:39 - Redirecting http://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:43 - Redirecting https://www.secretchamber.sg/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:47 - Redirecting http://www.secretchamber.sg -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:50 - Redirecting https://www.secretchamber.sg -> https://secretchamber.sg/
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735B70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yvkzbcjo
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yvkzbcjo
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yvkzbcjo
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/zspepkzc
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x047351F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/zspepkzc
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/zspepkzc
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735B10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yuwsupoq
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047356F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yuwsupoq
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047357B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-bin/cgiecho/yuwsupoq
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/lwfsvqze
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/lwfsvqze
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /cgi-sys/cgiecho/lwfsvqze
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x047351B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735B90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03C6DE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03C55E30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04735250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735890>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x047358B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
15036 - 04-Feb-20 00:11:58 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04735BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
